# Generated by Django 3.2.12 on 2022-03-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='is_contributor',
            field=models.BooleanField(default=False),
        ),
    ]
