# Generated by Django 3.2.12 on 2022-03-18 08:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_project_project_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_contributors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
