# Generated by Django 3.2.12 on 2022-03-18 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_management', '0003_alter_project_project_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_contributors',
        ),
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='project_contributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
