# Generated by Django 3.2.12 on 2022-03-24 14:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_label_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaskSprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_name', models.CharField(max_length=255)),
                ('sprint_start_date', models.DateTimeField(default=datetime.datetime(2022, 3, 24, 16, 30, 33, 614809))),
                ('sprint_end_date', models.DateTimeField(default=datetime.datetime(2022, 3, 24, 16, 30, 33, 614809))),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_story_name', models.CharField(max_length=255)),
                ('user_story_description', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_description', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('is_blocked_by', models.CharField(max_length=255)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_stories_app.tasksprint')),
                ('task_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_stories_app.tasklabel')),
                ('task_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_stories_app.taskstatus')),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_stories_app.userstory')),
            ],
        ),
    ]
