# Generated by Django 3.2.12 on 2022-03-24 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_stories_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksprint',
            name='sprint_end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 16, 32, 4, 490096)),
        ),
        migrations.AlterField(
            model_name='tasksprint',
            name='sprint_start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 16, 32, 4, 490096)),
        ),
    ]
